# Generated by Django 3.1.3 on 2020-11-28 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=95)),
                ('email', models.EmailField(max_length=35)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, choices=[('clothing', 'Clothing'), ('electronics', 'Electronics'), ('food', 'Food')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None)),
                ('adrress', models.CharField(max_length=95)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=35)),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.CharField(max_length=10)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None)),
                ('adrress', models.CharField(max_length=95)),
                ('city', models.CharField(max_length=35)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=35)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productimage')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
